version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      # API Key management and auth security defaults
      - VERIFY_API_KEYS=false
      - JWT_ALGORITHM=HS256
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - app-network

  # Frontend Next.js service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    command: npm run dev

  # PostgreSQL service for data storage
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=anime_companion
    restart: unless-stopped
    networks:
      - app-network

  # Redis service for caching and session management
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app-network
    command: redis-server --save 60 1 --loglevel warning

# Shared persistent volumes
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

# Shared networks
networks:
  app-network:
    driver: bridge 