version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=mongodb://mongodb:27017/anime_companion
      # API Key management and auth security defaults
      - VERIFY_API_KEYS=false
      - JWT_ALGORITHM=HS256
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network

  # Frontend Next.js service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - PORT=3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network
    command: npm run dev

  # MongoDB service for data storage
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

# Shared persistent volumes
volumes:
  mongodb_data:
    driver: local

# Shared networks
networks:
  app-network:
    driver: bridge 